name: pull-ticker-info
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests os
      - run: python search.py
