name: pull-ticker-info
on: [push]
jobs:
  pull-ticker-info:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - run: ticker=XAW.TO python search.py
        env:
          alphaToken: ${{ secrets.alphaToken }}
      - name: setup git config
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: commit
        run: |
          # Stage the file, commit and push
          git add .
          git commit -m "Update Data"
          git push origin ${{ github.head_ref }}
