name: pull-ticker-info
on: 
  push:
    branches:
      - '*'
  schedule:
    # ┌───────────── minute (0 - 59)
    # │ ┌───────────── hour (0 - 23)
    # │ │ ┌───────────── day of the month (1 - 31)
    # │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
    # │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    # │ │ │ │ │                                   
    # │ │ │ │ │
    # │ │ │ │ │
    # * * * * *
    - cron:  '0 0 * * 1-5'
jobs:
  pull-ticker-info:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - run: ticker=XAW.TO python search.py
        env:
          alphaToken: ${{ secrets.alphaToken }}
      - run: ticker=VCN.TO python search.py
        env:
          alphaToken: ${{ secrets.alphaToken }}
      - run: ticker=ZAG.TO python search.py
        env:
          alphaToken: ${{ secrets.alphaToken }}
      - run: ticker=VEQT.TO python search.py
        env:
          alphaToken: ${{ secrets.alphaToken }}
      - run: ticker=VT python search.py
        env:
          alphaToken: ${{ secrets.alphaToken }}
      - name: setup git config
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: commit
        run: |
          # Stage the file, commit and push
          git add .
          git commit -m "Update Data"
          git push origin ${{ github.head_ref }}
